# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-25 15:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=300)),
                ('category', models.CharField(max_length=200)),
                ('tags', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('companyName', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('tagline', models.CharField(max_length=200)),
                ('start_time', models.TimeField(default=django.utils.timezone.now)),
                ('end_time', models.TimeField(default=django.utils.timezone.now)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('role', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=100)),
                ('path', models.FileField(default='/media/none.jpg', upload_to='photos/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Requestjob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WT', 'Wait'), ('AC', 'Accept'), ('DE', 'Decline')], default='WT', max_length=9)),
                ('processed', models.BooleanField(default=0)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffapp.Job')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staffapp.Profile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
