# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-09-26 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='staff_members',
            field=models.ManyToManyField(default=[], to='staffapp.Profile'),
        ),
    ]
