# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0005_requestjob_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='end_job',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='job',
            name='start_job',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
