# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0007_auto_20170923_0344'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='path',
            field=models.FileField(default='/photo/none.jpg', upload_to='photos/'),
        ),
    ]
