# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staffapp', '0008_profile_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='path',
            field=models.FileField(default='/photos/none.jpg', upload_to='photos/'),
        ),
    ]
